# MagicLantern Build Environment

FROM armv7/armhf-ubuntu
MAINTAINER matteopic

RUN apt-get update && \
    apt-get install mercurial sudo wget curl doxygen zip nano -yq && \
	       cd /usr/src && \ 
	       hg clone -u unified https://bitbucket.org/hudson/magic-lantern

RUN apt-get install build-essential less bzip2 -yq && \
       curl -L -o /usr/src/gcc-arm-none-eabi-4_8-2013q4-20131204-src.tar.bz2 https://launchpad.net/gcc-arm-embedded/4.8/4.8-2013-q4-major/+download/gcc-arm-none-eabi-4_8-2013q4-20131204-src.tar.bz2 && \
	      tar -xvjf /usr/src/gcc-arm-none-eabi-4_8-2013q4-20131204-src.tar.bz2 -C /usr/src

# Exactly like <Magic Lantern>/contrib/toolchain/prepare.ubuntu.sh, but without sudo and without prompt user for confirmation
RUN apt-get install flex bison libgmp3-dev libmpfr-dev libncurses5-dev libmpc-dev autoconf texinfo build-essential git-core mercurial zlibc zlib1g-dev && \
    apt-get install python-matplotlib python-matplotlib-data python-matplotlib-doc python-matplotlib-dbg texlive-luatex python-docutils texlive-latex-base texlive-latex-recommended texlive-fonts-extra dvi2ps texlive-math-extra pandoc texlive-latex-extra ruby-full poppler-utils imagemagick

RUN      cd /usr/src/magic-lantern/contrib/toolchain && \
      chmod 744 summon-arm && \
./summon-arm



# Avoid CPAN prompt user for confirmation
ENV PERL_MM_USE_DEFAULT=1
ENV PERL_EXTUTILS_AUTOINSTALL="--defaultdeps"

RUN apt-get install perl python -yq && \
       perl -MCPAN -e 'install File::Slurp'

	
	
# disassemble.pl from http://chdk.wikia.com/wiki/GPL:disassemble.pl
ADD disassemble.pl /usr/bin

# Patch from http://www.magiclantern.fm/forum/index.php?topic=12177.0
ADD disassemble.pl.patch /tmp

RUN patch /usr/bin/disassemble.pl /tmp/disassemble.pl.patch && \
    chmod 744 /usr/bin/disassemble.pl

	
	

# Compile QEMU environment
RUN apt-get install pkg-config zlib1g zlib1g-dev libsdl-image1.2-dev bison flex autoconf -yq

RUN      cd /usr/src/magic-lantern/contrib/qemu && \
       echo Y | ./install.sh && \
	       cd /usr/src/qemu/qemu-1.6.0 && \
	./configure --target-list=arm-softmmu --disable-docs --enable-sdl
	
